import type { ItemContext } from "./types";

const allChannels = { resell: true, refurbish: true, exchange: true, donate: true, recycle: true };

type Seed = Partial<ItemContext> & Pick<ItemContext, "returnId" | "product" | "category" | "basePrice">;

const seeds: Seed[] = [
  {
    returnId: "RT-20481",
    product: "Urban Utility Jacket",
    category: "Outerwear",
    basePrice: 4800,
    condition: "good",
    season: "in_season",
    demand: "high",
    inventory: "normal",
    location: "Delhi Fulfilment Centre",
    returnReason: "Size issue",
    returnDate: "2026-09-04",
    processingCost: 120,
    refurbishmentCost: 420,
    logisticsCost: 180,
  },
  {
    returnId: "RT-20482",
    product: "Classic Straight Jeans",
    category: "Denim",
    basePrice: 2600,
    condition: "good",
    season: "transition",
    demand: "moderate",
    inventory: "excess",
    location: "Mumbai Fulfilment Centre",
    returnReason: "Fit not as expected",
    returnDate: "2026-09-04",
    processingCost: 90,
    refurbishmentCost: 260,
    logisticsCost: 150,
  },
  {
    returnId: "RT-20483",
    product: "Everyday Cotton Tee",
    category: "Tops",
    basePrice: 899,
    condition: "repairable",
    season: "in_season",
    demand: "moderate",
    inventory: "excess",
    location: "Bengaluru Hub",
    returnReason: "Stitching defect",
    returnDate: "2026-09-05",
    processingCost: 60,
    refurbishmentCost: 140,
    logisticsCost: 80,
  },
  {
    returnId: "RT-20484",
    product: "Performance Activewear Set",
    category: "Activewear",
    basePrice: 3200,
    condition: "new",
    season: "in_season",
    demand: "high",
    inventory: "shortage",
    location: "Gurugram Micro-hub",
    returnReason: "Wrong item shipped",
    returnDate: "2026-09-05",
    processingCost: 110,
    refurbishmentCost: 300,
    logisticsCost: 140,
  },
  {
    returnId: "RT-20485",
    product: "Linen Kurta",
    category: "Ethnic",
    basePrice: 2100,
    condition: "damaged",
    season: "out_of_season",
    demand: "low",
    inventory: "excess",
    location: "Jaipur Fulfilment Centre",
    returnReason: "Colour bleed after wash",
    returnDate: "2026-09-06",
    processingCost: 80,
    refurbishmentCost: 520,
    logisticsCost: 160,
    channels: { ...allChannels, refurbish: true, donate: false },
  },
  {
    returnId: "RT-20486",
    product: "Merino Crew Sweater",
    category: "Knitwear",
    basePrice: 3900,
    condition: "good",
    season: "out_of_season",
    demand: "low",
    inventory: "excess",
    location: "Delhi Fulfilment Centre",
    returnReason: "Changed mind",
    returnDate: "2026-09-06",
    processingCost: 120,
    refurbishmentCost: 380,
    logisticsCost: 190,
  },
  {
    returnId: "RT-20487",
    product: "Tailored Wool Blazer",
    category: "Formalwear",
    basePrice: 7400,
    condition: "repairable",
    season: "in_season",
    demand: "high",
    inventory: "shortage",
    location: "Mumbai Fulfilment Centre",
    returnReason: "Button missing",
    returnDate: "2026-09-06",
    processingCost: 160,
    refurbishmentCost: 640,
    logisticsCost: 220,
  },
  {
    returnId: "RT-20488",
    product: "Denim Overshirt",
    category: "Denim",
    basePrice: 3100,
    condition: "severely_damaged",
    season: "transition",
    demand: "moderate",
    inventory: "normal",
    location: "Bengaluru Hub",
    returnReason: "Tear across back panel",
    returnDate: "2026-09-07",
    processingCost: 90,
    refurbishmentCost: 900,
    logisticsCost: 140,
  },
  {
    returnId: "RT-20489",
    product: "Silk Blend Saree",
    category: "Ethnic",
    basePrice: 8900,
    condition: "good",
    season: "in_season",
    demand: "high",
    inventory: "normal",
    location: "Jaipur Fulfilment Centre",
    returnReason: "Delivery delay",
    returnDate: "2026-09-07",
    processingCost: 180,
    refurbishmentCost: 700,
    logisticsCost: 260,
  },
  {
    returnId: "RT-20490",
    product: "Quilted Puffer Vest",
    category: "Outerwear",
    basePrice: 4300,
    condition: "damaged",
    season: "in_season",
    demand: "moderate",
    inventory: "normal",
    location: "Delhi Fulfilment Centre",
    returnReason: "Zip broken",
    returnDate: "2026-09-07",
    processingCost: 130,
    refurbishmentCost: 480,
    logisticsCost: 180,
  },
  {
    returnId: "RT-20491",
    product: "Cotton Chino Trousers",
    category: "Bottoms",
    basePrice: 2400,
    condition: "good",
    season: "transition",
    demand: "moderate",
    inventory: "normal",
    location: "Gurugram Micro-hub",
    returnReason: "Length issue",
    returnDate: "2026-09-08",
    processingCost: 90,
    refurbishmentCost: 220,
    logisticsCost: 130,
  },
  {
    returnId: "RT-20492",
    product: "Ribbed Knit Dress",
    category: "Dresses",
    basePrice: 3600,
    condition: "new",
    season: "in_season",
    demand: "moderate",
    inventory: "excess",
    location: "Mumbai Fulfilment Centre",
    returnReason: "Ordered two sizes",
    returnDate: "2026-09-08",
    processingCost: 110,
    refurbishmentCost: 300,
    logisticsCost: 160,
  },
  {
    returnId: "RT-20493",
    product: "Oversized Hoodie",
    category: "Tops",
    basePrice: 2900,
    condition: "repairable",
    season: "transition",
    demand: "low",
    inventory: "excess",
    location: "Bengaluru Hub",
    returnReason: "Print peeling",
    returnDate: "2026-09-08",
    processingCost: 90,
    refurbishmentCost: 620,
    logisticsCost: 140,
  },
  {
    returnId: "RT-20494",
    product: "Leather Ankle Boots",
    category: "Footwear",
    basePrice: 6200,
    condition: "good",
    season: "transition",
    demand: "high",
    inventory: "shortage",
    location: "Delhi Fulfilment Centre",
    returnReason: "Size issue",
    returnDate: "2026-09-09",
    processingCost: 150,
    refurbishmentCost: 500,
    logisticsCost: 210,
  },
  {
    returnId: "RT-20495",
    product: "Printed Rayon Shirt",
    category: "Tops",
    basePrice: 1700,
    condition: "severely_damaged",
    season: "out_of_season",
    demand: "low",
    inventory: "excess",
    location: "Jaipur Fulfilment Centre",
    returnReason: "Fabric burn mark",
    returnDate: "2026-09-09",
    processingCost: 70,
    refurbishmentCost: 480,
    logisticsCost: 120,
    channels: { ...allChannels, recycle: false, donate: false },
  },
  {
    returnId: "RT-20496",
    product: "Wide-leg Palazzo",
    category: "Bottoms",
    basePrice: 2200,
    condition: "good",
    season: "in_season",
    demand: "moderate",
    inventory: "normal",
    location: "Gurugram Micro-hub",
    returnReason: "Changed mind",
    returnDate: "2026-09-09",
    processingCost: 80,
    refurbishmentCost: 200,
    logisticsCost: 120,
  },
  {
    returnId: "RT-20497",
    product: "Technical Rain Shell",
    category: "Outerwear",
    basePrice: 5600,
    condition: "repairable",
    season: "in_season",
    demand: "high",
    inventory: "normal",
    location: "Mumbai Fulfilment Centre",
    returnReason: "Seam leak",
    returnDate: "2026-09-10",
    processingCost: 140,
    refurbishmentCost: 560,
    logisticsCost: 200,
  },
  {
    returnId: "RT-20498",
    product: "Linen Shorts",
    category: "Bottoms",
    basePrice: 1500,
    condition: "damaged",
    season: "out_of_season",
    demand: "low",
    inventory: "excess",
    location: "Bengaluru Hub",
    returnReason: "Stain on hem",
    returnDate: "2026-09-10",
    processingCost: 60,
    refurbishmentCost: 340,
    logisticsCost: 100,
  },
  {
    returnId: "RT-20499",
    product: "Embroidered Sherwani",
    category: "Ethnic",
    basePrice: 12500,
    condition: "good",
    season: "in_season",
    demand: "high",
    inventory: "shortage",
    location: "Delhi Fulfilment Centre",
    returnReason: "Alteration requested",
    returnDate: "2026-09-10",
    processingCost: 220,
    refurbishmentCost: 900,
    logisticsCost: 300,
  },
  {
    returnId: "RT-20500",
    product: "Everyday Canvas Sneakers",
    category: "Footwear",
    basePrice: 2800,
    condition: "damaged",
    season: "transition",
    demand: "moderate",
    inventory: "normal",
    location: "Gurugram Micro-hub",
    returnReason: "Sole separation",
    returnDate: "2026-09-10",
    processingCost: 100,
    refurbishmentCost: 300,
    logisticsCost: 140,
  },
];

export const RETURNS: ItemContext[] = seeds.map((s) => ({
  location: "Delhi Fulfilment Centre",
  returnReason: "Not specified",
  returnDate: "2026-09-04",
  condition: "good",
  season: "in_season",
  demand: "moderate",
  inventory: "normal",
  processingCost: 100,
  refurbishmentCost: 300,
  logisticsCost: 150,
  qcVerified: true,
  channels: allChannels,
  ...s,
})) as ItemContext[];

export const LOCATIONS = [
  "Delhi Fulfilment Centre",
  "Mumbai Fulfilment Centre",
  "Bengaluru Hub",
  "Gurugram Micro-hub",
  "Jaipur Fulfilment Centre",
];

export function getReturn(id: string) {
  return RETURNS.find((r) => r.returnId === id);
}

export type ScenarioPreset = {
  id: string;
  name: string;
  note: string;
  patch: Partial<ItemContext>;
};

/** Guaranteed demo scenarios for RT-20481. */
export const PRESETS: ScenarioPreset[] = [
  {
    id: "s1",
    name: "Scenario 1 — In-season, good condition",
    note: "Expected: Resell",
    patch: { condition: "good", season: "in_season", demand: "high", inventory: "normal" },
  },
  {
    id: "s2",
    name: "Scenario 2 — Repairable, reasonable repair cost",
    note: "Expected: Refurbish",
    patch: {
      condition: "repairable",
      demand: "moderate",
      season: "in_season",
      inventory: "normal",
      refurbishmentCost: 420,
    },
  },
  {
    id: "s3",
    name: "Scenario 3 — Severely damaged, recycler available",
    note: "Expected: Recycle",
    patch: {
      condition: "severely_damaged",
      demand: "low",
      season: "transition",
      inventory: "normal",
      channels: { resell: true, refurbish: true, exchange: true, donate: true, recycle: true },
    },
  },
  {
    id: "s4",
    name: "Scenario 4 — Recycling channel disabled",
    note: "Expected: Write-off",
    patch: {
      condition: "severely_damaged",
      demand: "low",
      season: "transition",
      inventory: "normal",
      channels: { resell: true, refurbish: true, exchange: true, donate: false, recycle: false },
    },
  },
];
